/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.1
 * Generated at: 2019-10-06 04:11:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.chat.graduated.vo.Uservo;
import java.util.ArrayList;

public final class makegroup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/hestia/Desktop/chattest/graduated/graduatedchat/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Graduated/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1564482954169L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.chat.graduated.vo.Uservo");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String searchid = (String) session.getAttribute("searchid");
	System.out.println("makegroup -> " + searchid);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("    <meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\"\r\n");
      out.write("\tintegrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("<style>\r\n");
      out.write(".filebox input[type=\"file\"] {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\twidth: 1px;\r\n");
      out.write("\theight: 1px;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tmargin: -1px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tclip: rect(0, 0, 0, 0);\r\n");
      out.write("\tborder: 0;\r\n");
      out.write("}\r\n");
      out.write(".filebox label {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tpadding: .5em .75em;\r\n");
      out.write("\tcolor: #999;\r\n");
      out.write("\tfont-size: inherit;\r\n");
      out.write("\tline-height: normal;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tbackground-color: #fdfdfd;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tborder: 1px solid #ebebeb;\r\n");
      out.write("\tborder-bottom-color: #e2e2e2;\r\n");
      out.write("\tborder-radius: .25em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".filebox .upload-name {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tpadding: .5em .75em;\r\n");
      out.write("\t/* label의 패딩값과 일치 */\r\n");
      out.write("\tfont-size: inherit;\r\n");
      out.write("\tfont-family: inherit;\r\n");
      out.write("\tline-height: normal;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tbackground-color: #f5f5f5;\r\n");
      out.write("\tborder: 1px solid #ebebeb;\r\n");
      out.write("\tborder-bottom-color: #e2e2e2;\r\n");
      out.write("\tborder-radius: .25em;\r\n");
      out.write("\t-webkit-appearance: none;\r\n");
      out.write("\t/* 네이티브 외형 감추기 */\r\n");
      out.write("\t-moz-appearance: none;\r\n");
      out.write("\tappearance: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<script>\r\n");
      out.write("\tfunction Back() {\r\n");
      out.write("\t\twindow.history.back();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).on('click', '#btnSearch', function(e){\r\n");
      out.write("\te.preventDefault();\r\n");
      out.write("\tvar url = \"makegroup\";\r\n");
      out.write("\tlocation.href = url;\r\n");
      out.write("\tconsole.log(url);\r\n");
      out.write("});\t\r\n");
      out.write("</script>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t<!-- search{s} -->\r\n");
      out.write("\t<div class=\"form-group row justify-content-center\">\r\n");
      out.write("\t\t<div class=\"w300\" style=\"padding-right: 10px\">\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control form-control-sm\"\r\n");
      out.write("\t\t\t\tname=\"keyword\" id=\"keyword\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<button class=\"btn btn-sm btn-primary\" name=\"btnSearch\"\r\n");
      out.write("\t\t\t\tid=\"btnSearch\">검색</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- search{e} -->\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-3\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<form action=\"make_group\" method=\"get\" class=\"col-md-6\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<p class=\"h2 text-center\">Group</p>\r\n");
      out.write("\t\t\t\t<div class=\"preview text-center\">\r\n");
      out.write("\t\t\t\t\t<img class=\"preview-img\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"http://simpleicon.com/wp-content/uploads/account.png\"\r\n");
      out.write("\t\t\t\t\t\talt=\"Preview Image\" width=\"200\" height=\"200\" />\r\n");
      out.write("\t\t\t\t\t<div class=\"browse-button\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-pencil-alt\"></i>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"filebox\">\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"upload-name\" value=\"파일선택\" disabled=\"disabled\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"ex_filename\">업로드</label> <input type=\"file\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"ex_filename\" class=\"upload-hidden\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<span class=\"Error\"></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label>그룹이름:</label> <input class=\"form-control\" name=\"groupname\"\r\n");
      out.write("\t\t\t\t\t\ttype=\"text\" required placeholder=\"Enter Your Full Name\" /> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"Error\"></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<a href=\"memberadd\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-outline-success btn-xs pull-right\"><b>+</b>멤버추가</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<table class=\"table table-striped custab\">\r\n");
      out.write("\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>이름</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>ID</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th class=\"text-center\">Action</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>test ");
      out.print(searchid);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>News Cate</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"text-center\"><a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn btn-danger btn-xs\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-remove\"></span> Del</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Products</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Main Products</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"text-center\"><a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn btn-danger btn-xs\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-remove\"></span> Del</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Blogs</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Parent Blogs</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"text-center\"><a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn btn-danger btn-xs\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-remove\"></span>Del</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<input class=\"btn btn-outline-success btn-block\" type=\"submit\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"만들기\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Optional JavaScript -->\r\n");
      out.write("\t<!-- jQuery first, then Popper.js, then Bootstrap JS -->\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html> ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
