/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.1
 * Generated at: 2019-06-09 06:17:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/./sidebar.jsp", Long.valueOf(1559883934194L));
    _jspx_dependants.put("jar:file:/C:/Users/hestia/Desktop/chattest/graduated/graduatedchat/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Graduated/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1554194380912L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/group.css\">\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/chat.css\">\r\n");
      out.write("<style>\r\n");
      out.write("div h3 span{\r\n");
      out.write("     color : #FFF;\r\n");
      out.write("     font-size:14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div span {\r\n");
      out.write("     font-weight: 200;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1{\r\n");
      out.write("     font-weight: 200;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login_box{\r\n");
      out.write("    background: #f32d27; /* Old browsers */\r\n");
      out.write("    /* IE9 SVG, needs conditional override of 'filter' to 'none' */\r\n");
      out.write("    background: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgdmlld0JveD0iMCAwIDEgMSIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+CiAgPGxpbmVhckdyYWRpZW50IGlkPSJncmFkLXVjZ2ctZ2VuZXJhdGVkIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgeDE9IjAlIiB5MT0iMTAwJSIgeDI9IjEwMCUiIHkyPSIwJSI+CiAgICA8c3RvcCBvZmZzZXQ9IjUlIiBzdG9wLWNvbG9yPSIjZjMyZDI3IiBzdG9wLW9wYWNpdHk9IjEiLz4KICAgIDxzdG9wIG9mZnNldD0iOTklIiBzdG9wLWNvbG9yPSIjZmY2YjQ1IiBzdG9wLW9wYWNpdHk9IjEiLz4KICA8L2xpbmVhckdyYWRpZW50PgogIDxyZWN0IHg9IjAiIHk9IjAiIHdpZHRoPSIxIiBoZWlnaHQ9IjEiIGZpbGw9InVybCgjZ3JhZC11Y2dnLWdlbmVyYXRlZCkiIC8+Cjwvc3ZnPg==);\r\n");
      out.write("    background: -moz-linear-gradient(45deg,  #f32d27 5%, #ff6b45 99%); /* FF3.6+ */\r\n");
      out.write("    background: -webkit-gradient(linear, left bottom, right top, color-stop(5%,#f32d27), color-stop(99%,#ff6b45)); /* Chrome,Safari4+ */\r\n");
      out.write("    background: -webkit-linear-gradient(45deg,  #f32d27 5%,#ff6b45 99%); /* Chrome10+,Safari5.1+ */\r\n");
      out.write("    background: -o-linear-gradient(45deg,  #f32d27 5%,#ff6b45 99%); /* Opera 11.10+ */\r\n");
      out.write("    background: -ms-linear-gradient(45deg,  #f32d27 5%,#ff6b45 99%); /* IE10+ */\r\n");
      out.write("    background: linear-gradient(45deg,  #f32d27 5%,#ff6b45 99%); /* W3C */\r\n");
      out.write("    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f32d27', endColorstr='#ff6b45',GradientType=1 ); /* IE6-8 fallback on horizontal gradient */\r\n");
      out.write("    \r\n");
      out.write("    width:100%;\r\n");
      out.write("   /* height:70%; */\r\n");
      out.write("  \r\n");
      out.write("    <!--top:15%;-->\r\n");
      out.write("    left:32.5%;\r\n");
      out.write("    \r\n");
      out.write("    -webkit-box-shadow: 0px 0px 8px 0px rgba(50, 50, 50, 0.54);\r\n");
      out.write("-moz-box-shadow:    0px 0px 8px 0px rgba(50, 50, 50, 0.54);\r\n");
      out.write("box-shadow:         0px 0px 8px 0px rgba(50, 50, 50, 0.54);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (max-width: 767px) {\r\n");
      out.write("    .login_box{\r\n");
      out.write("        background: #f32d27; /* Old browsers */\r\n");
      out.write("        /* IE9 SVG, needs conditional override of 'filter' to 'none' */\r\n");
      out.write("        background: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgdmlld0JveD0iMCAwIDEgMSIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+CiAgPGxpbmVhckdyYWRpZW50IGlkPSJncmFkLXVjZ2ctZ2VuZXJhdGVkIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgeDE9IjAlIiB5MT0iMTAwJSIgeDI9IjEwMCUiIHkyPSIwJSI+CiAgICA8c3RvcCBvZmZzZXQ9IjUlIiBzdG9wLWNvbG9yPSIjZjMyZDI3IiBzdG9wLW9wYWNpdHk9IjEiLz4KICAgIDxzdG9wIG9mZnNldD0iOTklIiBzdG9wLWNvbG9yPSIjZmY2YjQ1IiBzdG9wLW9wYWNpdHk9IjEiLz4KICA8L2xpbmVhckdyYWRpZW50PgogIDxyZWN0IHg9IjAiIHk9IjAiIHdpZHRoPSIxIiBoZWlnaHQ9IjEiIGZpbGw9InVybCgjZ3JhZC11Y2dnLWdlbmVyYXRlZCkiIC8+Cjwvc3ZnPg==);\r\n");
      out.write("        background: -moz-linear-gradient(45deg,  #f32d27 5%, #ff6b45 99%); /* FF3.6+ */\r\n");
      out.write("        background: -webkit-gradient(linear, left bottom, right top, color-stop(5%,#f32d27), color-stop(99%,#ff6b45)); /* Chrome,Safari4+ */\r\n");
      out.write("        background: -webkit-linear-gradient(45deg,  #f32d27 5%,#ff6b45 99%); /* Chrome10+,Safari5.1+ */\r\n");
      out.write("        background: -o-linear-gradient(45deg,  #f32d27 5%,#ff6b45 99%); /* Opera 11.10+ */\r\n");
      out.write("        background: -ms-linear-gradient(45deg,  #f32d27 5%,#ff6b45 99%); /* IE10+ */\r\n");
      out.write("        background: linear-gradient(45deg,  #f32d27 5%,#ff6b45 99%); /* W3C */\r\n");
      out.write("        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f32d27', endColorstr='#ff6b45',GradientType=1 ); /* IE6-8 fallback on horizontal gradient */\r\n");
      out.write("        \r\n");
      out.write("        width:100%;\r\n");
      out.write("        height:80%;\r\n");
      out.write("  \r\n");
      out.write("        <!--top:10%;-->\r\n");
      out.write("        left:5%;\r\n");
      out.write("        \r\n");
      out.write("        -webkit-box-shadow: 0px 0px 8px 0px rgba(50, 50, 50, 0.54);\r\n");
      out.write("-moz-box-shadow:    0px 0px 8px 0px rgba(50, 50, 50, 0.54);\r\n");
      out.write("box-shadow:         0px 0px 8px 0px rgba(50, 50, 50, 0.54);\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".image-circle{\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    width: 175px;\r\n");
      out.write("    height: 175px;\r\n");
      out.write("    border: 4px solid #FFF;\r\n");
      out.write("    margin: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".follow{\r\n");
      out.write("    background-color:#FC563B;\r\n");
      out.write("    height: 80px;\r\n");
      out.write("    cursor:pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".follow:hover {\r\n");
      out.write("    background-color:#F22F26;\r\n");
      out.write("    height: 80px;\r\n");
      out.write("    cursor:pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login_control{\r\n");
      out.write("    background-color:#FFF;\r\n");
      out.write("    padding:10px;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".control {\r\n");
      out.write("    color:#000;\r\n");
      out.write("    margin:10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".label {\r\n");
      out.write("    \r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".form-control:focus{\r\n");
      out.write("    border-radius: 0px;\r\n");
      out.write("    border-bottom: 1px solid #FC563B;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("    outline: none;\r\n");
      out.write("    -webkit-box-shadow: none !important;\r\n");
      out.write("    -moz-box-shadow: none !important;\r\n");
      out.write("    box-shadow: none !important;\r\n");
      out.write("}\r\n");
      out.write(".btn-orange{\r\n");
      out.write("    background-color: #FC563B;\r\n");
      out.write("    border-radius: 0px;\r\n");
      out.write("    margin: 5px;\r\n");
      out.write("    padding: 5px;\r\n");
      out.write("    width: 150px;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    font-weight: inherit;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-orange:hover {\r\n");
      out.write("    background-color: #F22F26;\r\n");
      out.write("    border-radius: 0px;\r\n");
      out.write("    margin: 5px;\r\n");
      out.write("    padding: 5px;\r\n");
      out.write("    width: 150px;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    font-weight: inherit;\r\n");
      out.write("    color:#FFF !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".line{\r\n");
      out.write("    border-bottom : 2px solid #F32D27;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".outter{\r\n");
      out.write("    padding: 0px;\r\n");
      out.write("    border: 1px solid rgba(255, 255, 255, 0.29);\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    width: 200px;\r\n");
      out.write("    height: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function showdel(aa){\r\n");
      out.write("\t var con = document.getElementById(aa);\r\n");
      out.write("\t if( con.style.display == 'block'){\r\n");
      out.write("\t  con.style.display = 'none';\r\n");
      out.write("\t }\r\n");
      out.write("\t else{\r\n");
      out.write("\t  con.style.display = 'block';\r\n");
      out.write("\t }\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/sidebar.css\">\r\n");
      out.write("\r\n");
      out.write("  <header class=\"header\">\r\n");
      out.write("          <nav class=\"navbar navbar-toggleable-md navbar-light pt-0 pb-0 \">\r\n");
      out.write("            <button class=\"navbar-toggler navbar-toggler-right\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNavDropdown\" aria-controls=\"navbarNavDropdown\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <a class=\"navbar-brand p-0 mr-5\" href=\"#\" style=\"visibility:hidden \"><img src=\"http://via.placeholder.com/61x14\"></a>\r\n");
      out.write("            <div class=\"float-left\"> <a href=\"#\" class=\"button-left\"><span class=\"fa fa-fw fa-bars \" style=\"visibility:hidden \"></span></a> </div>\r\n");
      out.write("            <div class=\"collapse navbar-collapse flex-row-reverse\" id=\"navbarNavDropdown\">\r\n");
      out.write("              <ul class=\"navbar-nav\">\r\n");
      out.write("              <li class=\"nav-item dropdown messages-menu\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                  <a class=\"nav-link dropdown-toggle\" href=\"success\">\r\n");
      out.write("                    <i class=\"fa fa-home\" aria-hidden=\"true\"></i>\r\n");
      out.write("                  </a>\r\n");
      out.write("                 \r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item dropdown messages-menu\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                  <a class=\"nav-link dropdown-toggle\" href=\"calender\">\r\n");
      out.write("                    <i class=\"fa fa-calendar-check-o\" aria-hidden=\"true\"></i>\r\n");
      out.write("                    <span class=\"label label-success bg-success\">10</span>\r\n");
      out.write("                  </a>\r\n");
      out.write("                 \r\n");
      out.write("              </li>\r\n");
      out.write("                <li class=\"nav-item dropdown messages-menu\">\r\n");
      out.write("                  <a class=\"nav-link dropdown-toggle\" href=\"http://example.com\" id=\"navbarDropdownMenuLink\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                    <i class=\"fa fa-bell-o\"></i>\r\n");
      out.write("                    <span class=\"label label-success bg-success\">10</span>\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("                    <ul class=\"dropdown-menu-over list-unstyled\">\r\n");
      out.write("                      <li class=\"header-ul text-center\">You have 4 messages</li>\r\n");
      out.write("                      <li>\r\n");
      out.write("                        <!-- inner menu: contains the actual data -->\r\n");
      out.write("                        <ul class=\"menu list-unstyled\">\r\n");
      out.write("                          <li><!-- start message -->\r\n");
      out.write("                          <a href=\"#\">\r\n");
      out.write("                            <div class=\"pull-left\">\r\n");
      out.write("                              <img src=\"http://via.placeholder.com/160x160\" class=\"rounded-circle  \" alt=\"User Image\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h4>\r\n");
      out.write("                            Support Team\r\n");
      out.write("                            <small><i class=\"fa fa-clock-o\"></i> 5 mins</small>\r\n");
      out.write("                            </h4>\r\n");
      out.write("                            <p>Why not buy a new awesome theme?</p>\r\n");
      out.write("                          </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <!-- end message -->\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a href=\"#\">\r\n");
      out.write("                            <div class=\"pull-left\">\r\n");
      out.write("                              <img src=\"http://via.placeholder.com/160x160\" class=\"rounded-circle \" alt=\"User Image\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h4>\r\n");
      out.write("                            AdminLTE Design Team\r\n");
      out.write("                            <small><i class=\"fa fa-clock-o\"></i> 2 hours</small>\r\n");
      out.write("                            </h4>\r\n");
      out.write("                            <p>Why not buy a new awesome theme?</p>\r\n");
      out.write("                          </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a href=\"#\">\r\n");
      out.write("                            <div class=\"pull-left\">\r\n");
      out.write("                              <img src=\"http://via.placeholder.com/160x160\" class=\"rounded-circle \" alt=\"User Image\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h4>\r\n");
      out.write("                            Developers\r\n");
      out.write("                            <small><i class=\"fa fa-clock-o\"></i> Today</small>\r\n");
      out.write("                            </h4>\r\n");
      out.write("                            <p>Why not buy a new awesome theme?</p>\r\n");
      out.write("                          </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a href=\"#\">\r\n");
      out.write("                            <div class=\"pull-left\">\r\n");
      out.write("                              <img src=\"http://via.placeholder.com/160x160\" class=\"rounded-circle \" alt=\"User Image\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h4>\r\n");
      out.write("                            Sales Department\r\n");
      out.write("                            <small><i class=\"fa fa-clock-o\"></i> Yesterday</small>\r\n");
      out.write("                            </h4>\r\n");
      out.write("                            <p>Why not buy a new awesome theme?</p>\r\n");
      out.write("                          </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a href=\"#\">\r\n");
      out.write("                            <div class=\"pull-left\">\r\n");
      out.write("                              <img src=\"http://via.placeholder.com/160x160\" class=\"rounded-circle \" alt=\"User Image\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h4>\r\n");
      out.write("                            Reviewers\r\n");
      out.write("                            <small><i class=\"fa fa-clock-o\"></i> 2 days</small>\r\n");
      out.write("                            </h4>\r\n");
      out.write("                            <p>Why not buy a new awesome theme?</p>\r\n");
      out.write("                          </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"footer-ul text-center\"><a href=\"#\">See All Messages</a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item dropdown notifications-menu\">\r\n");
      out.write("                <a class=\"nav-link dropdown-toggle\" href=\"http://example.com\" id=\"navbarDropdownMenuLink\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                  <i class=\"fa fa-envelope-o\"></i>\r\n");
      out.write("                  <span class=\"label label-warning bg-warning\">10</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("                  <ul class=\"dropdown-menu-over list-unstyled\">\r\n");
      out.write("                    <li class=\"header-ul text-center\">You have 10 notifications</li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <!-- inner menu: contains the actual data -->\r\n");
      out.write("                      <ul class=\"menu list-unstyled\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a href=\"#\">\r\n");
      out.write("                            <i class=\"fa fa-users text-aqua\"></i> 5 new members joined today\r\n");
      out.write("                          </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a href=\"#\">\r\n");
      out.write("                            <i class=\"fa fa-warning text-yellow\"></i> Very long description here that may not fit into the\r\n");
      out.write("                            page and may cause design problems\r\n");
      out.write("                          </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a href=\"#\">\r\n");
      out.write("                            <i class=\"fa fa-users text-red\"></i> 5 new members joined\r\n");
      out.write("                          </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a href=\"#\">\r\n");
      out.write("                            <i class=\"fa fa-shopping-cart text-green\"></i> 25 sales made\r\n");
      out.write("                          </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a href=\"#\">\r\n");
      out.write("                            <i class=\"fa fa-user text-red\"></i> You changed your username\r\n");
      out.write("                          </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"footer-ul text-center\"><a href=\"messageview\">View all</a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("              </li>\r\n");
      out.write("              \r\n");
      out.write("              <li class=\"nav-item dropdown  user-menu\">\r\n");
      out.write("                <a class=\"nav-link dropdown-toggle\" href=\"http://example.com\" id=\"navbarDropdownMenuLink\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                  <img src=\"http://via.placeholder.com/160x160\" class=\"user-image\" alt=\"User Image\" >\r\n");
      out.write("                  <span class=\"hidden-xs\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("                  <a class=\"dropdown-item\" href=\"#\">Action</a>\r\n");
      out.write("                  <a class=\"dropdown-item\" href=\"#\">Another action</a>\r\n");
      out.write("                  <a class=\"dropdown-item\" href=\"#\">Something else here</a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("      </header>\r\n");
      out.write("      <div class=\"main\">\r\n");
      out.write("        <aside>\r\n");
      out.write("          <div class=\"sidebar left \">\r\n");
      out.write("            \r\n");
      out.write("            <ul class=\"list-sidebar bg-defoult\">\r\n");
      out.write("    \r\n");
      out.write("         \r\n");
      out.write("            <li> <a href=\"personal\" class=\"collapsed active\" > <i class=\"fa fa-users fa-3x\"></i> <span class=\"nav-label\">Change</span> </a></li>\r\n");
      out.write("         \r\n");
      out.write("              \r\n");
      out.write("            <li> <a href=\"group\"><i class=\"fa fa-plus fa-3x\"></i> <span class=\"nav-label\">GAdd</span></a> </li>\r\n");
      out.write("            <li> <a href=\"useradd\" class=\"collapsed active\" > <i class=\"fa fa-user-plus fa-3x\"></i> <span class=\"nav-label\">UAdd</span>  </a></li>\r\n");
      out.write("          <li> <a href=\"#\"><i class=\"fa fa-user-times fa-3x\"></i> <span class=\"nav-label\">Delete</span></a> </li>\r\n");
      out.write("          <li> <a href=\"logout\" class=\"collapsed active\" ><i class=\"fa fa-sign-out fa-3x\"></i> <span class=\"nav-label\">Signout</span></a></li>\r\n");
      out.write("       \r\n");
      out.write("        \r\n");
      out.write("  \r\n");
      out.write("    </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    </aside>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("<div class=\"col-2\"></div>\r\n");
      out.write("\t\t\t<div class=\"col-10\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"col-md-4 \">\r\n");
      out.write("\t<div class=\"row login_box\">\r\n");
      out.write("\t    <div class=\"col-md-12 col-xs-12\" align=\"center\">\r\n");
      out.write("            <div class=\"line\"><h3>&nbsp</h3></div>\r\n");
      out.write("            <div class=\"outter\"><img src=\"http://lorempixel.com/output/people-q-c-100-100-1.jpg\" class=\"image-circle\"/></div>   \r\n");
      out.write("            <h1 style=\"color:#fff\">Hi Guest</h1>\r\n");
      out.write("            <span style=\"color:#fff\">INDIAN</span>\r\n");
      out.write("\t    </div>\r\n");
      out.write("        <div><h3>&nbsp</h3></div>\r\n");
      out.write("        <div class=\"col-md-12 col-xs-12 login_control\">\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"control\">\r\n");
      out.write("                    <div class=\"label\">Email Address</div>\r\n");
      out.write("                    admin@gmail.com\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!--<div class=\"control\">\r\n");
      out.write("                     <div class=\"label\">Password</div>\r\n");
      out.write("                    <input type=\"password\" class=\"form-control\" value=\"123456\"/>\r\n");
      out.write("                </div>\r\n");
      out.write("\t\t\t\t<div class=\"control\">\r\n");
      out.write("                     <div class=\"label\">Confirm Password</div>\r\n");
      out.write("                    <input type=\"password\" class=\"form-control\" value=\"123456\"/>\r\n");
      out.write("                </div>-->\r\n");
      out.write("             <div align=\"center\">\r\n");
      out.write("                     <button class=\"btn btn-orange\" style=\"color:#fff\" onclick=\"showdel('aaa')\">채팅</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        </div>    \r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-lg-8 col-sm-6\"style=\"background-color:#fff\" id=\"aaa\">\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("  <div class=\"col-md-2\"></div>\r\n");
      out.write("    <div class=\"col-md-8 order-md-1\" >\r\n");
      out.write("   \r\n");
      out.write("      <form class=\"needs-validation\" novalidate>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"mb-3\">\r\n");
      out.write("          <label for=\"user\"  style=\"color:#000\">이름</label>\r\n");
      out.write("          <input type=\"text\" class=\"form-control\" id=\"user\" value=\"홍길동\" required>\r\n");
      out.write("          <div class=\"invalid-feedback\">\r\n");
      out.write("            Please enter a valid email address for shipping updates.\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"mb-3\">\r\n");
      out.write("          <label for=\"email\"  style=\"color:#000\">이메일</label>\r\n");
      out.write("          <input type=\"email\" class=\"form-control\" id=\"email\" placeholder=\"example@naver.com\" value=\"gildong@naver.com\">\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("\r\n");
      out.write("        <div class=\" mb-3\">\r\n");
      out.write("            <label for=\"zip\"  style=\"color:#000\">아이디</label>\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" id=\"zip\" placeholder=\"admin\" readonly>\r\n");
      out.write("            <div class=\"invalid-feedback\">\r\n");
      out.write("              Zip code required.\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("     \r\n");
      out.write("\t\t\r\n");
      out.write("   \r\n");
      out.write("          <div class=\" mb-3\">\r\n");
      out.write("            <label for=\"zip\"  style=\"color:#000\">비밀번호</label>\r\n");
      out.write("            <input type=\"password\" class=\"form-control\" id=\"zip\" >\r\n");
      out.write("            <div class=\"invalid-feedback\">\r\n");
      out.write("              Zip code required.\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\t\t   <div class=\"mb-3\">\r\n");
      out.write("            <label for=\"zip\"  style=\"color:#000\">비밀번호확인</label>\r\n");
      out.write("            <input type=\"password\" class=\"form-control\" id=\"zip\" >\r\n");
      out.write("            <div class=\"invalid-feedback\">\r\n");
      out.write("              Zip code required.\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("     \r\n");
      out.write("        <hr class=\"mb-4\">\r\n");
      out.write("        <button class=\"btn btn-outline-success btn-lg btn-block\" type=\"submit\">수정하기</button>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\" integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\" integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
